spring:
  autoconfigure:
    exclude:
      # Remove these exclusions if you'd like to use JPA for database functionality
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
