on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  verify-job:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/devcontainers/universal:focal
    steps:
      - run: ./topLevelVerify.sh

